name: GitHub Actions Demo1

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**' # Ignore changes in .github folder
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
  schedule:
    - cron: '15 6 * * 0' # Run every Sunday at 6:15 UTC
  workflow_dispatch: # Manually trigger the workflow

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

